# Generated by Django 4.0.5 on 2022-07-27 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 6, 54, 50, 978844, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 6, 54, 50, 978844, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_subject',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(),
        ),
    ]
