# Generated by Django 4.0.5 on 2022-07-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_comment_post_date_alter_post_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_date',
            new_name='comment_date',
        ),
    ]
